//
// AddProvider.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AddProvider: Codable {

    public var result: Int?
    public var error: String?
    public var speed: Int?

    public init(result: Int?, error: String?, speed: Int?) {
        self.result = result
        self.error = error
        self.speed = speed
    }


}

