//
// AssignVKToAppID.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AssignVKToAppID: Codable {

    public var result: Int?
    public var speed: Int?

    public init(result: Int?, speed: Int?) {
        self.result = result
        self.speed = speed
    }


}

