//
// BackLine.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BackLine: Codable {

    public var _id: String?
    public var capt: String?

    public init(_id: String?, capt: String?) {
        self._id = _id
        self.capt = capt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case capt
    }

}

