//
// Buttons.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Buttons: Codable {

    public var _left: [Left]?
    public var _right: [Right]?

    public init(_left: [Left]?, _right: [Right]?) {
        self._left = _left
        self._right = _right
    }

    public enum CodingKeys: String, CodingKey { 
        case _left = "left"
        case _right = "right"
    }

}

