//
// CntListItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CntListItem: Codable {

    public var type: String?
    public var cnt: String?

    public init(type: String?, cnt: String?) {
        self.type = type
        self.cnt = cnt
    }


}

