//
// ExportPeers.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ExportPeers: Codable {

    public var peers: [Peers]?
    public var result: Int?
    public var speed: Int?

    public init(peers: [Peers]?, result: Int?, speed: Int?) {
        self.peers = peers
        self.result = result
        self.speed = speed
    }


}

