//
// GetOKAppID.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetOKAppID: Codable {

    public var appId: String?
    public var appKey: String?
    public var result: Int?
    public var speed: Int?

    public init(appId: String?, appKey: String?, result: Int?, speed: Int?) {
        self.appId = appId
        self.appKey = appKey
        self.result = result
        self.speed = speed
    }

    public enum CodingKeys: String, CodingKey { 
        case appId = "app_id"
        case appKey = "app_key"
        case result
        case speed
    }

}

