//
// GetProviderPostsPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetProviderPostsPaging: Codable {

    public var posts: [Post]?
    public var result: Int?
    public var speed: Int?

    public init(posts: [Post]?, result: Int?, speed: Int?) {
        self.posts = posts
        self.result = result
        self.speed = speed
    }


}

