//
// GetProviderReviewsPaging.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetProviderReviewsPaging: Codable {

    public var revs: [Reviews]?
    public var result: Int?
    public var speed: Int?

    public init(revs: [Reviews]? = nil, result: Int? = nil, speed: Int? = nil) {
        self.revs = revs
        self.result = result
        self.speed = speed
    }


}

