//
// GetStep.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class GetStep: Codable, ObservableObject {

    public var stepId: Int?
    public var type: String?
    public var capt: String?
    public var hint: String?
    public var descr: String?
    public var ansqers: [Answer]?
    public var captListExists: String?
    public var captListExtButton: String?
    public var captListName: String?
    public var edtPlaceHolder: String?
    public var result: Int?
    public var backStepId: String?
    public var speed: Int?

  public var answers: [Answer] {
    ansqers ?? []
  }
  
    public init(stepId: Int? = nil, type: String? = nil, capt: String? = nil, hint: String? = nil, descr: String? = nil, ansqers: [Answer]? = nil, captListExists: String? = nil, captListExtButton: String? = nil, captListName: String? = nil, edtPlaceHolder: String? = nil, result: Int? = nil, backStepId: String? = nil, speed: Int? = nil) {
        self.stepId = stepId
        self.type = type
        self.capt = capt
        self.hint = hint
        self.descr = descr
        self.ansqers = ansqers
        self.captListExists = captListExists
        self.captListExtButton = captListExtButton
        self.captListName = captListName
        self.edtPlaceHolder = edtPlaceHolder
        self.result = result
        self.backStepId = backStepId
        self.speed = speed
    }

    public enum CodingKeys: String, CodingKey { 
        case stepId = "step_id"
        case type
        case capt
        case hint
        case descr
        case ansqers
        case captListExists = "capt_list_exists"
        case captListExtButton = "capt_list_ext_button"
        case captListName = "capt_list_name"
        case edtPlaceHolder = "edt_place_holder"
        case result
        case backStepId = "back_step_id"
        case speed
    }

}

