//
// GetSearchPage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSearchPage: Codable {

    public var help: Help?
    public var cntList: [CntListItem]?
    public var query: String?
    public var pg: String?
    public var export: Export?
    public var posts: [Post]?
    public var result: Int?
    public var speed: Int?

    public init(help: Help?, cntList: [CntListItem]?, query: String?, pg: String?, export: Export?, posts: [Post]?, result: Int?, speed: Int?) {
        self.help = help
        self.cntList = cntList
        self.query = query
        self.pg = pg
        self.export = export
        self.posts = posts
        self.result = result
        self.speed = speed
    }

    public enum CodingKeys: String, CodingKey { 
        case help
        case cntList = "cnt_list"
        case query
        case pg
        case export
        case posts
        case result
        case speed
    }

}

