//
// GetStep.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetStep: Codable {

    public var stepId: Int?
    public var type: String?
    public var capt: String?
    public var hint: String?
    public var descr: String?
    public var ansqers: [Answer]?
    public var result: Int?
    public var backStepId: String?
    public var speed: Int?

    public init(stepId: Int?, type: String?, capt: String?, hint: String?, descr: String?, ansqers: [Answer]?, result: Int?, backStepId: String?, speed: Int?) {
        self.stepId = stepId
        self.type = type
        self.capt = capt
        self.hint = hint
        self.descr = descr
        self.ansqers = ansqers
        self.result = result
        self.backStepId = backStepId
        self.speed = speed
    }

    public enum CodingKeys: String, CodingKey { 
        case stepId = "step_id"
        case type
        case capt
        case hint
        case descr
        case ansqers
        case result
        case backStepId = "back_step_id"
        case speed
    }

}

