//
// GetUserProfile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct GetUserProfile: Codable {
  
  public var msg: String?
  public var user: UserProfile?
  public var result: Int?
  public var speed: Int?
  
  public init(msg: String?, user: UserProfile?, result: Int?, speed: Int?) {
    self.msg = msg
    self.user = user
    self.result = result
    self.speed = speed
  }
}
