//
// HelpPage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct HelpPage: Codable {

    public var help: [HelpItem]?
    public var result: Int?
    public var speed: Int?

    public init(help: [HelpItem]?, result: Int?, speed: Int?) {
        self.help = help
        self.result = result
        self.speed = speed
    }


}

