//
// HelpItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct HelpItem: Codable {

    public var _id: String?
    public var capt: String?
    public var text: String?
    public var url: String?

    public init(_id: String?, capt: String?, text: String?, url: String?) {
        self._id = _id
        self.capt = capt
        self.text = text
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case capt
        case text
        case url
    }

}

