//
// Help.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Help: Codable {

    public var str: String?
    public var url: String?

    public init(str: String?, url: String?) {
        self.str = str
        self.url = url
    }


}

