//
// InputValue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InputValue: Codable {

    public var placeHolder: String?
    public var defVal: String?
    public var canEdit: Int?
    public var maxLen: Int?

    public init(placeHolder: String?, defVal: String?, canEdit: Int?, maxLen: Int?) {
        self.placeHolder = placeHolder
        self.defVal = defVal
        self.canEdit = canEdit
        self.maxLen = maxLen
    }

    public enum CodingKeys: String, CodingKey { 
        case placeHolder = "place_holder"
        case defVal = "def_val"
        case canEdit = "can_edit"
        case maxLen = "max_len"
    }

}

