//
// Left.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Left: Codable {

    public var _id: Int?
    public var capt: String?
    public var rec: Int?

    public init(_id: Int?, capt: String?, rec: Int?) {
        self._id = _id
        self.capt = capt
        self.rec = rec
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case capt
        case rec
    }

}

