//
// ListWorkList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ListWorkList: Codable {

    public var _id: Int?
    public var capt: String?
    public var subCapt: String?
    public var act: String?
    public var ext: Int?

    public init(_id: Int?, capt: String?, subCapt: String?, act: String?, ext: Int?) {
        self._id = _id
        self.capt = capt
        self.subCapt = subCapt
        self.act = act
        self.ext = ext
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case capt
        case subCapt = "sub_capt"
        case act
        case ext
    }

}

