//
// ListWork.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ListWork: Codable {

    public var list: [ListWorkList]?
    public var result: Int?
    public var speed: Int?

    public init(list: [ListWorkList]?, result: Int?, speed: Int?) {
        self.list = list
        self.result = result
        self.speed = speed
    }


}

