//
// Message.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Message: Codable {

    public var _id: Int?
    public var title: String?
    public var msg: String?

    public init(_id: Int?, title: String?, msg: String?) {
        self._id = _id
        self.title = title
        self.msg = msg
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case msg
    }

}

