//
// PostLike.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostLike: Codable {

    public var postLkCnt: String?
    public var result: Int?
    public var speed: Int?

    public init(postLkCnt: String?, result: Int?, speed: Int?) {
        self.postLkCnt = postLkCnt
        self.result = result
        self.speed = speed
    }

    public enum CodingKeys: String, CodingKey { 
        case postLkCnt = "post_lk_cnt"
        case result
        case speed
    }

}

