//
// Post.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct Post: Codable {
  
  public var _id: String?
  public var vendorCapt: String?
  public var vendorId: String?
  public var pointId: String?
  public var vkPost: String?
  public var price: String?
  public var by: String?
  public var like: String?
  public var views: String?
  public var posted: String?
  public var text: String?
  public var images: [Images]?
  public var sizes: [String]?
  public var options: [String]?
  
  var providerTitle: String {
    vendorCapt ?? ""
  }
  
  var providerName: String {
    by?.capitalized ?? ""
  }
  
  var cleanText: String {
    text?.replacingOccurrences(of: "<br>", with: "\n") ?? ""
  }
  
  var imageUrls: [String] {
    if let serverImages = images {
      var imageNames = [String]()
      for image in serverImages {
        if let imageName = image.image {
          imageNames.append(imageName)
        }
      }
      return imageNames
    } else {
      return []
    }
  }
  
  public init(_id: String? = nil, vendorCapt: String? = nil, vendorId: String? = nil, pointId: String? = nil, vkPost: String? = nil, price: String? = nil, by: String? = nil, like: String? = nil, views: String? = nil, posted: String? = nil, text: String? = nil, images: [Images]? = nil, sizes: [String]? = nil, options: [String]? = nil) {
    self._id = _id
    self.vendorCapt = vendorCapt
    self.vendorId = vendorId
    self.pointId = pointId
    self.vkPost = vkPost
    self.price = price
    self.by = by
    self.like = like
    self.views = views
    self.posted = posted
    self.text = text
    self.images = images
    self.sizes = sizes
    self.options = options
  }
  
  public enum CodingKeys: String, CodingKey {
    case _id = "id"
    case vendorCapt = "vendor_capt"
    case vendorId = "vendor_id"
    case pointId = "point_id"
    case vkPost = "vk_post"
    case price
    case by
    case like
    case views
    case posted
    case text
    case images
    case sizes
    case options
  }
}

extension Post: Identifiable {
  public var id: String {
    _id ?? UUID().uuidString
  }
}
