//
// Provider.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Provider: Codable {

    public var anonym: String?
    public var vendId: String?
    public var name: String?
    public var img: String?
    public var phone: String?
    public var placeId: String?
    public var vkLink: String?
    public var pop: String?
    public var regDt: String?
    public var terms: String?
    public var export: Export?
    public var revsInfo: ReviewsInfo?
    public var posts: [Post]?
    public var result: Int?
    public var speed: Int?

    public init(anonym: String?, vendId: String?, name: String?, img: String?, phone: String?, placeId: String?, vkLink: String?, pop: String?, regDt: String?, terms: String?, export: Export?, revsInfo: ReviewsInfo?, posts: [Post]?, result: Int?, speed: Int?) {
        self.anonym = anonym
        self.vendId = vendId
        self.name = name
        self.img = img
        self.phone = phone
        self.placeId = placeId
        self.vkLink = vkLink
        self.pop = pop
        self.regDt = regDt
        self.terms = terms
        self.export = export
        self.revsInfo = revsInfo
        self.posts = posts
        self.result = result
        self.speed = speed
    }

    public enum CodingKeys: String, CodingKey { 
        case anonym
        case vendId = "vend_id"
        case name
        case img
        case phone
        case placeId = "place_id"
        case vkLink = "vk_link"
        case pop
        case regDt = "reg_dt"
        case terms
        case export
        case revsInfo = "revs_info"
        case posts
        case result
        case speed
    }

}

