//
// ProvidersTop.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProvidersTop: Codable {

    public var help: Help?
    public var items: [ProviderItem]?
    public var result: Int?
    public var speed: Int?

    public init(help: Help?, items: [ProviderItem]?, result: Int?, speed: Int?) {
        self.help = help
        self.items = items
        self.result = result
        self.speed = speed
    }


}

