//
// ProviderItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProviderItem: Codable {

    public var vendId: String?
    public var dt: String?
    public var capt: String?
    public var name: String?
    public var pos: String?
    public var popularity: String?
    public var prices: String?
    public var pricesAvg: String?
    public var pointId: String?

    public init(vendId: String?, dt: String?, capt: String?, name: String?, pos: String?, popularity: String?, prices: String?, pricesAvg: String?, pointId: String?) {
        self.vendId = vendId
        self.dt = dt
        self.capt = capt
        self.name = name
        self.pos = pos
        self.popularity = popularity
        self.prices = prices
        self.pricesAvg = pricesAvg
        self.pointId = pointId
    }

    public enum CodingKeys: String, CodingKey { 
        case vendId = "vend_id"
        case dt
        case capt
        case name
        case pos
        case popularity
        case prices
        case pricesAvg = "prices_avg"
        case pointId = "point_id"
    }

}

