//
// ProviderLike.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProviderLike: Codable {

    public var vendsLkCnt: String?
    public var result: Int?
    public var speed: Int?

    public init(vendsLkCnt: String?, result: Int?, speed: Int?) {
        self.vendsLkCnt = vendsLkCnt
        self.result = result
        self.speed = speed
    }

    public enum CodingKeys: String, CodingKey { 
        case vendsLkCnt = "vends_lk_cnt"
        case result
        case speed
    }

}

