//
// ReviewImages.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReviewImages: Codable {

    public var _id: String?
    public var img: String?

    public init(_id: String?, img: String?) {
        self._id = _id
        self.img = img
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case img
    }

}

