//
// Reviews.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct Reviews: Codable, Identifiable {
  
  public var _id: String?
  public var author: String?
  public var rate: String?
  public var title: String?
  public var text: String?
  public var dt: String?
  public var imgs: [String]?
  
  public var id: String {
    _id ?? UUID().uuidString
  }
  
  public var rating: Double? {
    Double(rate ?? "0")
  }
  
  public var filledStars: Int {
    Int(rating ?? 0)
  }
  
  public var hasHalfStart: Bool {
    if let rating = rating {
      return rating > floor(rating)
    }
    
    return false
  }
  
  public var emptyStars: Int {
    5 - filledStars - (hasHalfStart ? 1 : 0)
  }
  
  var imageUrls: [String] {
    if let serverImages = imgs {
      return serverImages
    } else {
      return []
    }
  }
  
  public init(_id: String? = nil, author: String? = nil, rate: String? = nil, title: String? = nil, text: String? = nil, dt: String? = nil, imgs: [String]? = nil) {
    self._id = _id
    self.author = author
    self.rate = rate
    self.title = title
    self.text = text
    self.dt = dt
    self.imgs = imgs
  }
  
  public enum CodingKeys: String, CodingKey {
    case _id = "id"
    case author
    case rate
    case title
    case text
    case dt
    case imgs
  }  
}
