//
// Reviews.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Reviews: Codable {

    public var _id: String?
    public var author: String?
    public var rate: String?
    public var text: String?
    public var dt: String?
    public var imgs: [String]?

    public init(_id: String?, author: String?, rate: String?, text: String?, dt: String?, imgs: [String]?) {
        self._id = _id
        self.author = author
        self.rate = rate
        self.text = text
        self.dt = dt
        self.imgs = imgs
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case author
        case rate
        case text
        case dt
        case imgs
    }

}

