//
// ReviewsInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReviewsInfo: Codable {

    public var cnt: String?
    public var rate: String?
    public var imgsCnt: String?
    public var revs: [Reviews]?

    public init(cnt: String?, rate: String?, imgsCnt: String?, revs: [Reviews]?) {
        self.cnt = cnt
        self.rate = rate
        self.imgsCnt = imgsCnt
        self.revs = revs
    }

    public enum CodingKeys: String, CodingKey { 
        case cnt
        case rate
        case imgsCnt = "imgs_cnt"
        case revs
    }

}

