//
// Right.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Right: Codable {

    public var _id: Int?
    public var capt: String?

    public init(_id: Int?, capt: String?) {
        self._id = _id
        self.capt = capt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case capt
    }

}

