//
// ServerImage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ServerImage: Codable {


    public var n: String?

    public var w: Int?

    public var h: Int?
    public init(n: String? = nil, w: Int? = nil, h: Int? = nil) { 
        self.n = n
        self.w = w
        self.h = h
    }

}
