//
// SetInputValue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SetInputValue: Codable {

    public var stepId: Int?
    public var type: String?
    public var capt: String?
    public var hint: String?
    public var descr: String?
    public var inputVal: [InputValue]?
    public var buttons: [Buttons]?
    public var result: Int?
    public var speed: Int?

    public init(stepId: Int?, type: String?, capt: String?, hint: String?, descr: String?, inputVal: [InputValue]?, buttons: [Buttons]?, result: Int?, speed: Int?) {
        self.stepId = stepId
        self.type = type
        self.capt = capt
        self.hint = hint
        self.descr = descr
        self.inputVal = inputVal
        self.buttons = buttons
        self.result = result
        self.speed = speed
    }

    public enum CodingKeys: String, CodingKey { 
        case stepId = "step_id"
        case type
        case capt
        case hint
        case descr
        case inputVal = "input_val"
        case buttons
        case result
        case speed
    }

}

