//
// SetListSelect.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SetListSelect: Codable {

    public var stepId: Int?
    public var type: String?
    public var capt: String?
    public var hint: String?
    public var descr: String?
    public var items: [SetListSelectItems]?
    public var result: Int?
    public var speed: Int?

    public init(stepId: Int?, type: String?, capt: String?, hint: String?, descr: String?, items: [SetListSelectItems]?, result: Int?, speed: Int?) {
        self.stepId = stepId
        self.type = type
        self.capt = capt
        self.hint = hint
        self.descr = descr
        self.items = items
        self.result = result
        self.speed = speed
    }

    public enum CodingKeys: String, CodingKey { 
        case stepId = "step_id"
        case type
        case capt
        case hint
        case descr
        case items
        case result
        case speed
    }

}

