//
// SetListWork.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SetListWork: Codable {

    public var nextStepId: String?
    public var result: Int?
    public var speed: Int?

    public init(nextStepId: String?, result: Int?, speed: Int?) {
        self.nextStepId = nextStepId
        self.result = result
        self.speed = speed
    }

    public enum CodingKeys: String, CodingKey { 
        case nextStepId = "next_step_id"
        case result
        case speed
    }

}

