//
// SetListSelectItems.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SetListSelectItems: Codable {

    public var _id: Int?
    public var capt: String?
    public var hint: String?
    public var button: String?
    public var rec: Int?

    public init(_id: Int?, capt: String?, hint: String?, button: String?, rec: Int?) {
        self._id = _id
        self.capt = capt
        self.hint = hint
        self.button = button
        self.rec = rec
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case capt
        case hint
        case button
        case rec
    }

}

