//
// SetSimpleReq.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SetSimpleReq: Codable {

    public var nextStepId: String?
    public var err: String?
    public var message: String?
    public var result: Int?
    public var speed: Int?

    public init(nextStepId: String?, err: String?, message: String?, result: Int?, speed: Int?) {
        self.nextStepId = nextStepId
        self.err = err
        self.message = message
        self.result = result
        self.speed = speed
    }

    public enum CodingKeys: String, CodingKey { 
        case nextStepId = "next_step_id"
        case err
        case message
        case result
        case speed
    }

}

