//
// Spot.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Spot: Codable {

    public var anonym: String?
    public var pointId: String?
    public var capt: String?
    public var arrows: Arrows?
    public var backLine: BackLine?
    public var activity: TotalActivity?
    public var altertText: String?
    public var export: Export?
    public var vends: [Providers]?
    public var pointsTop: [TopSpot]?
    public var posts: [Post]?
    public var result: Int?
    public var speed: Int?

    public init(anonym: String?, pointId: String?, capt: String?, arrows: Arrows?, backLine: BackLine?, activity: TotalActivity?, altertText: String?, export: Export?, vends: [Providers]?, pointsTop: [TopSpot]?, posts: [Post]?, result: Int?, speed: Int?) {
        self.anonym = anonym
        self.pointId = pointId
        self.capt = capt
        self.arrows = arrows
        self.backLine = backLine
        self.activity = activity
        self.altertText = altertText
        self.export = export
        self.vends = vends
        self.pointsTop = pointsTop
        self.posts = posts
        self.result = result
        self.speed = speed
    }

    public enum CodingKeys: String, CodingKey { 
        case anonym
        case pointId = "point_id"
        case capt
        case arrows
        case backLine = "back_line"
        case activity
        case altertText = "altert_text"
        case export
        case vends
        case pointsTop = "points_top"
        case posts
        case result
        case speed
    }

}

