//
// TopLines.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TopLines: Codable {

    public var linesActTop: [TopLine]?
    public var anonymm: String?
    public var result: Int?
    public var speed: Int?

    public init(linesActTop: [TopLine]?, anonymm: String?, result: Int?, speed: Int?) {
        self.linesActTop = linesActTop
        self.anonymm = anonymm
        self.result = result
        self.speed = speed
    }

    public enum CodingKeys: String, CodingKey { 
        case linesActTop = "lines_act_top"
        case anonymm
        case result
        case speed
    }

}

