//
// TotalActivity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct TotalActivity: Codable {
  
  public var postToday: String?
  public var postYstd: String?
  public var photoToday: String?
  public var photoYstd: String?
  
  public init(postToday: String? = nil, postYstd: String? = nil, photoToday: String? = nil, photoYstd: String? = nil) {
    self.postToday = postToday
    self.postYstd = postYstd
    self.photoToday = photoToday
    self.photoYstd = photoYstd
  }
  
  public enum CodingKeys: String, CodingKey {
    case postToday = "post_today"
    case postYstd = "post_ystd"
    case photoToday = "photo_today"
    case photoYstd = "photo_ystd"
  }
}
